name: Haxe-Instrument

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '15 23 * * 1,3,6'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: ['4.2.5', '4.3.4', 'nightly']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set Git Auto CRLF to false on Windows
      if: matrix.platform == 'windows-latest'
      run: git config --global core.autocrlf false
    - name: Checkout Formatter sources
      uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Run npm install
      run: npm ci
    - name: Install Haxe version ${{ matrix.haxe-version }}
      run: |
        npx lix download haxe ${{ matrix.haxe-version }}
        npx lix use haxe ${{ matrix.haxe-version }}
    - name: Run lix download
      run: npx lix download
    - name: Print versions
      run: |
        npx haxe -version
        npx neko -version
        npx haxelib list
    - name: Run demo
      run: npx haxe build.hxml
    - name: Run self coverage
      run: npx haxe testSelfCoverage.hxml
    - name: Run tests
      run: npx haxe test.hxml
    - name: Upload results to codecov
      if: success() && matrix.platform == 'ubuntu-latest' && matrix.haxe-version == '4.3.4'
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
